name: publish_conda

on:
  release:
    types: [published]
  workflow_dispatch: # on demand
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: publish-to-conda
      uses: jegp/conda-package-publish-action@v1.6 #GiulioRossetti/conda-package-publish-action@v1.1.0
      with:
        subdir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        # platforms: 'all'
        override: true
        # dry_run: true
